//! Idempotent seeding of `historical_playoff_skater_totals` from a CSV
//! bundled into the binary via `include_str!`.
//!
//! The CSV (600 rows, ~36 KB) is the 5-year playoff aggregation used as a
//! regression-to-mean prior in the Bayesian player-projection blend. We
//! embed it rather than reading from disk because Fly deploys don't mount
//! the repo's `backend/data/` directory at runtime, and a 36 KB embed is
//! trivial on binary size.
//!
//! Called once at server startup from `main.rs`. If the table already has
//! rows the function returns quickly without touching the data — deploys
//! don't need to worry about duplicate inserts, and a future update to
//! the CSV requires manually truncating the table or bumping a seed
//! version.

use tracing::{info, warn};

use crate::db::FantasyDb;
use crate::error::{Error, Result};

/// CSV bundled at compile time. Regenerated by
/// `backend/scripts/parse_historical_playoff_skaters.py` from the raw
/// hockey-reference export.
const HISTORICAL_CSV: &str =
    include_str!("../../data/historical_playoff_skater_totals.csv");

/// Populate the table once if it's empty. Runs in the background during
/// startup so a cold server still boots fast.
pub async fn seed_historical_skaters_if_empty(db: &FantasyDb) -> Result<usize> {
    let existing: i64 = sqlx::query_scalar(
        "SELECT COUNT(*) FROM historical_playoff_skater_totals",
    )
    .fetch_one(db.pool())
    .await
    .map_err(Error::Database)?;

    if existing > 0 {
        info!(
            rows = existing,
            "historical_playoff_skater_totals already seeded, skipping"
        );
        return Ok(0);
    }

    let rows = parse_csv(HISTORICAL_CSV);
    if rows.is_empty() {
        warn!("historical CSV produced 0 rows after parse; skipping seed");
        return Ok(0);
    }

    // Batch insert in one statement — 600 rows is small enough that a
    // single UNNEST-driven INSERT keeps the code simple and the DB
    // round-trip count at 1.
    let names: Vec<&str> = rows.iter().map(|r| r.player_name.as_str()).collect();
    let borns: Vec<i32> = rows.iter().map(|r| r.born).collect();
    let teams: Vec<&str> = rows.iter().map(|r| r.team.as_str()).collect();
    let positions: Vec<&str> = rows.iter().map(|r| r.position.as_str()).collect();
    let gps: Vec<i32> = rows.iter().map(|r| r.gp).collect();
    let gs: Vec<i32> = rows.iter().map(|r| r.g).collect();
    let as_: Vec<i32> = rows.iter().map(|r| r.a).collect();
    let ps: Vec<i32> = rows.iter().map(|r| r.p).collect();
    let shots: Vec<Option<i32>> = rows.iter().map(|r| r.shots).collect();
    let tois: Vec<Option<i32>> = rows.iter().map(|r| r.toi_seconds).collect();

    let inserted = sqlx::query(
        r#"
        INSERT INTO historical_playoff_skater_totals (
            player_name, born, team, position, gp, g, a, p, shots, toi_seconds
        )
        SELECT * FROM UNNEST(
            $1::text[], $2::int[], $3::text[], $4::text[],
            $5::int[], $6::int[], $7::int[], $8::int[],
            $9::int[], $10::int[]
        )
        ON CONFLICT (player_name, born) DO NOTHING
        "#,
    )
    .bind(&names)
    .bind(&borns)
    .bind(&teams)
    .bind(&positions)
    .bind(&gps)
    .bind(&gs)
    .bind(&as_)
    .bind(&ps)
    .bind(&shots)
    .bind(&tois)
    .execute(db.pool())
    .await
    .map_err(Error::Database)?
    .rows_affected() as usize;

    info!(rows = inserted, "seeded historical_playoff_skater_totals");
    Ok(inserted)
}

#[derive(Debug, Clone)]
struct Row {
    player_name: String,
    born: i32,
    team: String,
    position: String,
    gp: i32,
    g: i32,
    a: i32,
    p: i32,
    shots: Option<i32>,
    toi_seconds: Option<i32>,
}

/// Minimal CSV reader — no quoted fields, no commas-in-values (the source
/// CSV is generated by our own Python script and is well-formed). A full
/// `csv` crate would work too but this avoids the dependency.
fn parse_csv(src: &str) -> Vec<Row> {
    let mut out = Vec::new();
    let mut lines = src.lines();
    let header = match lines.next() {
        Some(h) => h,
        None => return out,
    };
    // Validate header order so a hand-edit of the CSV that renumbers
    // columns fails loud at startup rather than silently inserting
    // shifted data.
    debug_assert_eq!(
        header,
        "player_name,team,position,born,gp,g,a,p,shots,toi_seconds"
    );

    for (i, line) in lines.enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        let fields: Vec<&str> = line.split(',').collect();
        if fields.len() != 10 {
            warn!(line = i + 2, got = fields.len(), "skipping malformed CSV row");
            continue;
        }
        let parse_i32 = |s: &str| -> Option<i32> {
            let t = s.trim();
            if t.is_empty() {
                None
            } else {
                t.parse::<i32>().ok()
            }
        };
        let Some(born) = parse_i32(fields[3]) else {
            continue;
        };
        let Some(gp) = parse_i32(fields[4]) else {
            continue;
        };
        out.push(Row {
            player_name: fields[0].to_string(),
            team: fields[1].to_string(),
            position: fields[2].to_string(),
            born,
            gp,
            g: parse_i32(fields[5]).unwrap_or(0),
            a: parse_i32(fields[6]).unwrap_or(0),
            p: parse_i32(fields[7]).unwrap_or(0),
            shots: parse_i32(fields[8]),
            toi_seconds: parse_i32(fields[9]),
        });
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_csv_parses_to_expected_row_count() {
        let rows = parse_csv(HISTORICAL_CSV);
        // The parser dedupes by skipping malformed rows, so the count must
        // be in a tight range — flags any accidental corruption of the CSV.
        assert!(
            rows.len() >= 500 && rows.len() <= 700,
            "expected ~600 rows, got {}",
            rows.len()
        );
    }

    #[test]
    fn parse_handles_missing_optional_fields() {
        let src = "player_name,team,position,born,gp,g,a,p,shots,toi_seconds\n\
                   A Player,TOR,F,1998,25,10,15,25,,";
        let rows = parse_csv(src);
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].player_name, "A Player");
        assert!(rows[0].shots.is_none());
        assert!(rows[0].toi_seconds.is_none());
    }

    #[test]
    fn parse_skips_rows_missing_required_fields() {
        let src = "player_name,team,position,born,gp,g,a,p,shots,toi_seconds\n\
                   Bad Row,,,,,,,,,\n\
                   Good Row,TOR,F,1998,25,10,15,25,,";
        let rows = parse_csv(src);
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].player_name, "Good Row");
    }
}
